# GitHub Pages Configuration for Cosmos Engine RPG HTML Rulebook
title: Cosmos Engine RPG - Second Edition
description: A science fiction tabletop RPG that scales from personal combat to galactic fleet operations
theme: null  # We're using custom CSS
baseurl: ""  # Set this if deploying to a project page (e.g., /cosmos-engine-rpg)

# Build settings
markdown: kramdown
exclude:
  - README.md
  - .gitignore
  - _config.yml

# Custom variables
version: "2.0.0"
last_updated: "2024"